
// List of music genres
export const musicGenres = [
  { value: 'alternative', label: 'Alternative' },
  { value: 'ambient', label: 'Ambient' },
  { value: 'blues', label: 'Blues' },
  { value: 'classical', label: 'Classical' },
  { value: 'comedy', label: 'Comedy/Spoken Word' },
  { value: 'country', label: 'Country' },
  { value: 'dance', label: 'Dance' },
  { value: 'drill', label: 'Drill' },
  { value: 'dubstep', label: 'Dubstep' },
  { value: 'edm', label: 'EDM' },
  { value: 'electronic', label: 'Electronic' },
  { value: 'folk', label: 'Folk' },
  { value: 'funk', label: 'Funk' },
  { value: 'gospel', label: 'Gospel' },
  { value: 'grime', label: 'Grime' },
  { value: 'hiphop', label: 'Hip-Hop/Rap' },
  { value: 'house', label: 'House' },
  { value: 'indie', label: 'Indie' },
  { value: 'instrumental', label: 'Instrumental' },
  { value: 'jazz', label: 'Jazz' },
  { value: 'jpop', label: 'J-Pop' },
  { value: 'kpop', label: 'K-Pop' },
  { value: 'latin', label: 'Latin' },
  { value: 'lofi', label: 'Lo-Fi' },
  { value: 'metal', label: 'Metal' },
  { value: 'opera', label: 'Opera' },
  { value: 'pop', label: 'Pop' },
  { value: 'punk', label: 'Punk' },
  { value: 'randb', label: 'R&B/Soul' },
  { value: 'reggae', label: 'Reggae' },
  { value: 'reggaeton', label: 'Reggaeton' },
  { value: 'rock', label: 'Rock' },
  { value: 'soundtrack', label: 'Soundtrack' },
  { value: 'techno', label: 'Techno' },
  { value: 'trance', label: 'Trance' },
  { value: 'trap', label: 'Trap' },
  { value: 'triphop', label: 'Trip-Hop' },
  { value: 'world', label: 'World' },
];

// Distribution platforms with IDs
export const distributionPlatforms = [
  { id: 'spotify', name: 'Spotify', logo: 'https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_Green.png' },
  { id: 'apple_music', name: 'Apple Music', logo: 'https://www.apple.com/v/apple-music/s/images/overview/apple_music_logo__8ks5x4qz75ua_large.png' },
  { id: 'youtube_music', name: 'YouTube Music', logo: 'https://music.youtube.com/img/on_platform_logo_dark.svg' },
  { id: 'amazon_music', name: 'Amazon Music', logo: 'https://m.media-amazon.com/images/G/01/digital/music/merch/2020/LandingPages/SiteRedesign/Amazon-Music-Logo_White.png' },
  { id: 'tidal', name: 'Tidal', logo: 'https://tidal.com/img/logo.svg' },
  { id: 'deezer', name: 'Deezer', logo: 'https://e-cdns-files.dzcdn.net/img/common/opengraph-logo.png' },
  { id: 'pandora', name: 'Pandora', logo: 'https://www.pandora.com/web-version/1.114.0/images/pandora_logo_light.svg' },
  { id: 'soundcloud', name: 'SoundCloud', logo: 'https://developers.soundcloud.com/assets/logo_white-af5006050dd9cba09b0c48be04feac57.png' },
  { id: 'beatport', name: 'Beatport', logo: 'https://www.beatport.com/static/7-f53a5ed/images/logo-white.svg' },
  { id: 'bandcamp', name: 'Bandcamp', logo: 'https://s4.bcbits.com/img/bandcamp-logo-bcw2.svg' },
  { id: 'traxsource', name: 'Traxsource', logo: 'https://www.traxsource.com/themes/alpha/img/traxsource-logo@2x.png' },
  { id: 'juno_download', name: 'Juno Download', logo: 'https://www.junodownload.com/images/juno/logo.png' },
  { id: 'boomplay', name: 'Boomplay', logo: 'https://assets.boomplaymusic.com/images/logo@4x.png' },
  { id: 'audiomack', name: 'Audiomack', logo: 'https://audiomack.com/newsroom/wp-content/uploads/2020/02/audiomack-orange-14.png' },
  { id: 'napster', name: 'Napster', logo: 'https://web.napster.com/ecom-web-static/1.5.0-hotfix.7/napster_logo.svg' },
  { id: 'anghami', name: 'Anghami', logo: 'https://www.anghami.com/assets/dist/img/anghami-logo-white.png' },
  { id: 'kkbox', name: 'KKBOX', logo: 'https://www.kkbox.com/about/img/logo_en.jpg' },
  { id: 'qobuz', name: 'Qobuz', logo: 'https://static.qobuz.com/img/logos/qobuz-logotype.svg' },
  { id: 'joox', name: 'JOOX', logo: 'https://www.joox.com/th-en/joox_web/images/logo_joox.svg' },
  { id: 'awesound', name: 'Awesound', logo: 'https://assets.awesound.com/assets/press/awesound-logo-100c7e7cb6e7cdb1a6ea676bcf6ea019cf14a0e2b1111ad2b9ab52c057cc517a.png' }
];
