// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwulskrkjrhxhsspcoxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dWxza3JranJoeGhzc3Bjb3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Mzg5NjksImV4cCI6MjA1NzExNDk2OX0.uh4Sb8uvi1VNeRTL8JdLVIabPvj1hDMl_dC1AVi4bTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);